<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>


<?php include 'menu.phtml'?>

   <?= $view_nome?>
     
<form method="post">
  <label>Nome completo</label>
  <input type="text" name="nome"><br>
  <label>E-mail</label>
  <input type="text" name="email"><br>
  <label>Senha</label>
  <input type="text" name="senha"><br>
  <label>Repetir senha</label>
  <input type="text" name="senha2"><br>
  <input type="submit" name="enviar">
</form>

<?php  include 'footer.phtml';?>
