<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Gerenciador</title>
</head>

<body>
	
<?php require_once 'menu.phtml';?>  <!--- INCLUDE DO MENU  --->

 <h1><?= $view_titulo ?></h1>
 
   <div id="formulario">
	  <form method="post">
	    <label>E-mail</label>
		<input type="text" name="login" /><br>
		<label>Senha</label>
		<input type="text" name="senha" /><br>
	    <input type="submit" name="enviar" />	 
	 </form>
   </div>
   
<?php require_once 'footer.phtml';?><!--- INCLUDE DO RODAPE  --->

<tr bgcolor=""></tr>