<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Gerenciador</title>

</head>

<body>
	
<?php require_once 'menu.phtml';?>  <!--- INCLUDE DO MENU  --->

 <div id="wrap-login">
 	 <h1><?= $view_titulo ?></h1>
   <div id="formulario">
	  <form method="post" class="form">
	    <input type="text" name="login" placeholder="E-mail" /><br>
        <input type="password"  name="senha"  placeholder="Senha" /><br>
        <a href="#">Esqueçeu sua senha? Clique aqui para recuperá-la.</a>
	    <input type="submit" name="enviar" value="Logar"   class="logar"/>	 
	 </form>
	 <p> <?= $view_msg ?> </p>
   </div>
</div>
<div id="footer">   
<?php require_once 'footer.phtml';?><!--- INCLUDE DO RODAPE  --->
</div>