<?php if(!isset($_SESSION['login']) AND (!isset($_SESSION['senha'] )))
{
	header('location:http://127.0.0.1/framework2');			  
} 

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link rel="stylesheet" href="<?php $this->BaseUrl()?>/framework2/web/css/style.css"  type="text/css" media="all">
</head>
<body>
	
<input type="hidden"  value="<?=  $view_user_id?>" />
 
 <?php require_once("adminmenu.phtml")?>
 
<?php  $lista = $view_list?>

<div id="header-user" style="margin-top: 10px; margin-bottom: 30px"> 
	 
 <a href="novousuario">Novo usúario</a>
 
<h1>Usúarios</h1>
 <table width="600px">
 	<thead>
 		<tr style="background: #eee">
 			<td></td>
 			<td>Status</td>
 			<td>Permissão</td>
 			<td>Nome</td>
 		    <td>E-mail</td>
 		</tr>
 	</thead>
 	<tbody>
 		 
 		<?php foreach($lista as $row){ ?>
 			<tr>
 			   <td>true</td>
 			   <td>ativo</td>
 			   <td><?php echo $row['per_nome']?></td>
 			   <td><?php echo  $row['usu_nome']?></td>
 			   <td><?php echo  $row['usu_usuario']?></td>
 		    </tr>
 		   <?php } ?>		
 		
 	</tbody>
 </table>

 
</div><!-- fim listUser-->


 <?php require_once("footer.phtml")?>